research_task:
  description: >
    Conduct comprehensive research on the topic "{topic}" to gather complete
    and relevant information for writing a book targeted at "{target_audience}".
    
    Your research must include:
    1. Basic information and historical context about the topic
    2. Current trends and recent developments
    3. Relevant statistics and data
    4. Expert quotes and authoritative sources
    5. Writing styles used by other authors on similar topics
    6. Examples of effective narrative approaches
    7. Useful bibliographic resources and references
    8. Controversial aspects or ongoing debates
    9. Interesting case studies or practical examples
    10. Technical terminology and key concepts to include
    
    Organize information in a structured way and always indicate sources.
    
  expected_output: >
    A complete and well-organized research report that includes:
    - Executive summary of key information
    - Thematic sections with detailed information
    - List of relevant quotes with attributions
    - Analysis of observed writing styles
    - Recommendations for narrative approach
    - Bibliography and consulted sources
    
    The report must be at least 2000 words and provide a solid foundation
    for book creation.

design_task:
  description: >
    Based on the provided research report, design the complete structure of a book
    on topic "{topic}" for target audience "{target_audience}" with length "{book_length}".
    
    Your design must include:
    1. Compelling and relevant main book title
    2. Explanatory subtitle (if necessary)
    3. General book structure (number of chapters, logical organization)
    4. Specific title for each chapter
    5. Brief description of each chapter's content (2-3 paragraphs)
    6. Narrative thread connecting all chapters
    7. Tone of voice and writing style to adopt
    8. Special elements to include (info boxes, quotes, examples)
    9. Target length for each chapter
    10. Notes for maintaining stylistic consistency
    
    IMPORTANT: You must determine the optimal number of chapters for this topic.
    Consider the book length, topic complexity, and target audience.
    Typical ranges:
    - Short books: 3-5 chapters
    - Medium books: 4-8 chapters  
    - Long books: 8-12 chapters
    
    Adapt complexity and language to the specified target audience.
    
  expected_output: >
    A complete design document that includes:
    - Book title and subtitle
    - Detailed table of contents with chapter titles
    - 2-3 paragraph description for each chapter
    - Stylistic and narrative guidelines
    - Technical specifications (length, tone, special elements)
    - Strategy for narrative consistency
    - Clear statement of total number of chapters chosen
    
    The design must be clear, detailed, and provide a complete roadmap
    for the writers. Make sure to explicitly state how many chapters
    the book will have.

# Chapter writing task template (used dynamically)
chapter_task_template:
  description: >
    Write Chapter {chapter_num} of the book following the structure defined by the designer.
    
    Use the research findings and design specifications from the previous tasks to inform your writing.
    
    Requirements:
    - Follow exactly the specifications for Chapter {chapter_num} from the design
    - Maintain consistency with the established tone and style
    - Use relevant information from the research
    - Write approximately 1500-3000 words for medium length books
    - Create engaging content that flows naturally
    - End with a smooth transition (unless it's the final chapter)
    
    Chapter number: {chapter_num}
    Total chapters: {total_chapters}
    
    {revision_instructions}
    
  expected_output: >
    A complete Chapter {chapter_num} that:
    - Follows the designer's specifications exactly
    - Is stylistically consistent with the overall book
    - Includes all elements specified in the design
    - Incorporates relevant research findings
    - Is engaging and flows well
    - Has appropriate length for the book type
    - Maintains narrative coherence
    {revision_requirements}

# Chapter review task template (used dynamically)
chapter_review_template:
  description: >
    Review Chapter {chapter_num} for quality, consistency, and correctness.
    Provide immediate, constructive feedback for the writer.
    
    CHAPTER CONTENT TO REVIEW:
    {chapter_content}
    
    Perform a detailed analysis focusing on:
    
    1. GRAMMAR AND SYNTAX:
       - Spelling and typing errors
       - Grammatical and punctuation errors
       - Sentence construction and text fluidity
       - Correct use of verb tenses
    
    2. CONTENT QUALITY:
       - Accuracy of presented information
       - Appropriateness for target audience
       - Completeness according to design specifications
       - Narrative flow and engagement
    
    3. CONSISTENCY:
       - Adherence to established tone and style
       - Consistency with previous chapters (if applicable)
       - Proper transitions and connections
    
    4. STRUCTURE:
       - Chapter organization and pacing
       - Appropriate length and depth
       - Clear introduction and conclusion
    
    If you find any issues, provide:
    - Specific identification of the problem with exact location
    - Explanation of why it's problematic
    - Concrete suggestion for correction
    - Priority level (HIGH/MEDIUM/LOW)
    
    Chapter number: {chapter_num}
    
  expected_output: >
    A detailed review report for Chapter {chapter_num} that includes:
    
    1. OVERALL ASSESSMENT:
       - Quality rating (EXCELLENT/GOOD/NEEDS_IMPROVEMENT/POOR)
       - Summary of main strengths
       - Summary of main issues
    
    2. SPECIFIC ISSUES FOUND:
       - List each problem with exact location
       - Categorize by type (grammar, content, consistency, structure)
       - Provide specific correction suggestions
       - Assign priority level
    
    3. RECOMMENDATIONS:
       - Required changes (HIGH priority)
       - Suggested improvements (MEDIUM/LOW priority)
       - Overall guidance for revision
    
    4. DECISION:
       - APPROVED: Chapter is ready for publication
       - MINOR_REVISIONS: Small changes needed
       - MAJOR_REVISIONS: Significant rewriting required
       - REJECT: Chapter needs to be completely rewritten
    
    Be constructive and specific in your feedback to help the writer improve the chapter effectively.

conclusion_task:
  description: >
    Write the book's conclusion that summarizes the key points covered in the
    previous chapters and provides a satisfying closure for the reader.
    
    Review all the chapters that have been written and approved to ensure
    your conclusion properly addresses the entire book content.
    
    The conclusion must:
    1. Summarize the main concepts of the book
    2. Connect all chapters in an overall vision
    3. Provide final reflections on the topic
    4. Include call-to-action or suggestions for the reader
    5. Leave a lasting and positive impression
    6. Maintain the tone of voice of the rest of the book
    7. Reference key points from each chapter
    8. Provide a sense of completion and fulfillment
    
  expected_output: >
    A compelling conclusion of 800-1500 words that:
    - Effectively summarizes the book's key themes
    - Connects all chapters in a cohesive narrative
    - Provides actionable next steps for readers
    - Maintains stylistic consistency with approved chapters
    - References specific insights from each chapter
    - Leaves readers satisfied and inspired
    - Creates a memorable and impactful ending

control_task:
  description: >
    Perform a comprehensive final review of the complete book to verify
    overall quality, consistency, and readiness for publication.
    This is the final quality gate before publication.
    
    Since individual chapters have already been reviewed and revised through
    the interactive process, focus on the book as a unified whole.
    
    Conduct a holistic review of the entire book, focusing on:
    
    OVERALL CONSISTENCY:
    1. Narrative thread throughout all chapters
    2. Consistent tone and style maintenance
    3. Logical progression from introduction to conclusion
    4. Coherent treatment of the main topic
    5. Smooth transitions between all chapters
    
    STRUCTURAL INTEGRITY:
    1. Adherence to original design specifications
    2. Balanced chapter lengths and content depth
    3. Effective chapter-to-chapter flow
    4. Strong introduction and conclusion
    5. Appropriate book length and pacing
    
    CONTENT COMPLETENESS:
    1. All required topics covered adequately
    2. Information accuracy and currency
    3. Appropriate depth for target audience
    4. Balanced treatment of different aspects
    5. No gaps or redundancies
    
    EDITORIAL QUALITY:
    1. Overall language quality and clarity
    2. Absence of repetition or contradictions
    3. Consistent terminology usage
    4. Professional presentation standards
    5. Reader engagement throughout
    
    PUBLICATION READINESS:
    1. Market appropriateness
    2. Commercial viability
    3. Competitive positioning
    4. Target audience satisfaction
    
  expected_output: >
    A comprehensive final quality report that includes:
    
    1. EXECUTIVE SUMMARY:
       - Overall quality assessment (EXCELLENT/GOOD/SATISFACTORY/NEEDS_WORK)
       - Publication recommendation (READY/MINOR_ADJUSTMENTS/MAJOR_REVISIONS)
       - Key strengths and achievements
    
    2. CONSISTENCY ANALYSIS:
       - Narrative flow evaluation
       - Style and tone consistency
       - Chapter-to-chapter coherence
       - Design adherence assessment
    
    3. CONTENT EVALUATION:
       - Topic coverage completeness
       - Information accuracy verification
       - Target audience appropriateness
       - Engagement and readability assessment
    
    4. STRUCTURAL REVIEW:
       - Book architecture effectiveness
       - Chapter balance and pacing
       - Introduction and conclusion strength
       - Overall organization quality
    
    5. FINAL RECOMMENDATIONS:
       - Publication decision with rationale
       - Any final adjustments needed
       - Marketing considerations
       - Competitive positioning notes
    
    6. REVISION PROCESS SUMMARY:
       - Overview of chapter revision cycles
       - Quality improvements achieved
       - Writer-controller collaboration effectiveness
       - Process efficiency evaluation
    
    If the book meets publication standards, declare it "APPROVED FOR PUBLICATION"
    with detailed justification. If not, provide specific guidance for final improvements.

final_evaluation:
  description: >
    As Editorial Director, provide a professional and comprehensive evaluation
    of the completed book, assigning a final grade based on industry-standard
    editorial criteria. This evaluation considers the enhanced quality achieved
    through the interactive writer-controller revision process.
    
    Evaluation criteria (each on 1-10 scale):
    
    1. WRITING QUALITY (25%)
       - Language fluidity and clarity
       - Vocabulary richness and appropriateness
       - Stylistic effectiveness and consistency
       - Grammar and technical accuracy
       - Benefit from revision process
    
    2. CONSISTENCY AND STRUCTURE (20%)
       - Logical content organization
       - Narrative consistency between chapters
       - Book architecture effectiveness
       - Transitions and connections
       - Adherence to original design
    
    3. CONTENT VALUE (25%)
       - Information depth and accuracy
       - Originality and insights
       - Relevance to target audience
       - Treatment completeness
       - Research integration quality
    
    4. ENGAGEMENT AND READABILITY (15%)
       - Ability to capture and maintain attention
       - Language accessibility
       - Narrative rhythm and pacing
       - Reader satisfaction potential
    
    5. TARGET APPROPRIATENESS (15%)
       - Tone appropriateness for audience
       - Adequate complexity level
       - Example relevance and effectiveness
       - Expectation satisfaction
    
    Calculate final grade as weighted average of criteria.
    
    Final evaluation scale:
    - 9.0-10.0: Masterpiece (immediate publication, potential bestseller)
    - 8.0-8.9: Excellent (recommended publication, high market potential)
    - 7.0-7.9: Good (publishable, solid commercial prospects)
    - 6.0-6.9: Sufficient (publishable with market positioning)
    - 5.0-5.9: Below Standard (needs significant improvement)
    - <5.0: Unacceptable (major revision required)
    
  expected_output: >
    A professional editorial evaluation that includes:
    
    1. EXECUTIVE SUMMARY:
       - Final grade out of 10 with one decimal place
       - Quality category and market assessment
       - Publication recommendation with confidence level
       - Impact of interactive revision process
    
    2. DETAILED ANALYSIS BY CRITERIA:
       - Specific score for each criterion (1-10)
       - Detailed comments on strengths and achievements
       - Identification of any remaining improvement areas
       - Evidence of quality enhancement from revisions
    
    3. PROCESS EVALUATION:
       - Effectiveness of writer-controller interaction
       - Quality improvement through revision cycles
       - Comparison to traditional single-draft approach
       - Innovation and collaboration assessment
    
    4. STRENGTHS AND ACHIEVEMENTS:
       - Excellent aspects of the completed book
       - Distinctive and original elements
       - Competitive advantages in the market
       - Reader value proposition
    
    5. MARKET POSITIONING:
       - Target audience fit and appeal
       - Competitive landscape analysis
       - Commercial potential assessment
       - Marketing angle recommendations
    
    6. FINAL RECOMMENDATIONS:
       - Publication strategy suggestions
       - Marketing and positioning advice
       - Author development notes
       - Future project considerations
    
    7. QUALITY ASSURANCE NOTES:
       - Confirmation of publication readiness
       - Risk assessment for market success
       - Benchmark comparison with industry standards
       - Editorial process validation
    
    The evaluation must be objective, comprehensive, and reflect current
    publishing industry standards while highlighting the benefits of the
    collaborative revision process implemented.